// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI agent that analyzes and improves an uploaded credit dispute letter.
 *
 * - improveUploadedLetter - A function that takes a letter and returns an improved letter.
 * - ImproveUploadedLetterInput - The input type for the improveUploadedLetter function.
 * - ImproveUploadedLetterOutput - The return type for the improveUploadedLetter function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveUploadedLetterInputSchema = z.object({
  letterText: z
    .string()
    .describe('The text content of the credit dispute letter to improve.'),
});
export type ImproveUploadedLetterInput = z.infer<typeof ImproveUploadedLetterInputSchema>;

const ImproveUploadedLetterOutputSchema = z.object({
  improvedLetterText: z
    .string()
    .describe('The improved text content of the credit dispute letter.'),
});
export type ImproveUploadedLetterOutput = z.infer<typeof ImproveUploadedLetterOutputSchema>;

export async function improveUploadedLetter(input: ImproveUploadedLetterInput): Promise<ImproveUploadedLetterOutput> {
  return improveUploadedLetterFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveUploadedLetterPrompt',
  input: {schema: ImproveUploadedLetterInputSchema},
  output: {schema: ImproveUploadedLetterOutputSchema},
  prompt: `You are an expert in writing effective credit dispute letters.

  Please analyze the following credit dispute letter and improve it to increase its effectiveness. Focus on clarity, persuasiveness, and adherence to legal standards.

  Original Letter:
  {{{letterText}}}

  Improved Letter:`, //Crucially, you MUST NOT attempt to directly call functions, use `await` keywords, or perform any complex logic _within_ the Handlebars template string.
});

const improveUploadedLetterFlow = ai.defineFlow(
  {
    name: 'improveUploadedLetterFlow',
    inputSchema: ImproveUploadedLetterInputSchema,
    outputSchema: ImproveUploadedLetterOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
